# 1단계: 빌드 (Node.js)
FROM node:20 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# 2단계: 실행 (Nginx)
FROM nginx:alpine
# Vite 빌드 결과물 복사
COPY --from=build /app/dist /usr/share/nginx/html
# 작성한 Nginx 설정 파일 복사 (경로 확인 필수!)
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]