# backend/routing_system/Dockerfile
# 1단계: 빌드
FROM gradle:8-jdk17 AS build
WORKDIR /app
COPY . .
RUN ./gradlew clean build -x test

# 2단계: 실행
FROM eclipse-temurin:17-jre-jammy
WORKDIR /app
COPY --from=build /app/build/libs/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]